### ISSUE TITLE
baseURL and rootURL problem

### ISSUE THREAD

**Issue by leifdejong** [simplabs/ember-simple-auth#1048]
I recently updated ember to 2.7 and changed the baseURL to rootURL and added the baseURL to the simple auth config. Unfortunately ember simple auth goes into a login/logout loop although the session does authenticate successfully. When adding the baseURL: '/' back to environment.js, simple auth does exactly what it is supposed to. Would like to continue with Ember's recommended deprecation but this issue is causing us to stick with baseURL and ignore the warning. Any suggestions?

My main issue is that there are no assertions, no errors, no logs. Everything appears to work correctly to login until is automatically just logs out.

**Comment by AbdullaM5** [comment]
Possible i have same issue

**Comment by marcoow** [comment]
What does your ESA config look like? The `baseURL` property is actually supposed to be read-only although that's not properly reflected in the API docs.

**Comment by IgorKvasn** [comment]
Hi, 
not sure but I guess I am facing the same problem 

here are steps to reproduce (note that my application is running on with context `/abc` which is basically rootURL/baseURL)
1. navigate to `http://localhost:8080/abc` (note there is no slash at the end)
2. got redirected to `http://localhost:8080/abc/login` (which is fine)
3. when I login, I got immediately redirected back to `http://localhost:8080/abc/login` 
4.  when I now login (again!) everything is fine from now on

When in first step navigate to `http://localhost:8080/abc/` (note the slash at the end) - everything works fine.

my `config/environment.js` has rootURL: '/abc/' and there is no baseURL, however when I configure the baseURL as well, it still does not work

when I change my context from `/abc` to simple `/` (and change the rootURL/baseURL as well) - everything works fine

let me know when you need some more info

**Comment by marcoow** [comment]
@IgorKvasn: ESA only used the `rootURL`/`baseURL` on logout, never on login so I think what you're observing is probably not related to the issue described above.

**Comment by IgorKvasn** [comment]
@marcoow hmm thanks

**Comment by maxkwallace** [comment]
I didn't run into either of the issues leifdejong and IgorKvasn described, but when I upgraded to Ember 2.7, I did remove `baseURL` from my app entirely without realizing that ESA still relied on it.

As marcoow points out, ESA uses `baseURL` on logout:

```
  sessionInvalidated() {
    if (!Ember.testing) {
      window.location.replace(Configuration.baseURL);
    }
  }
```

In my case, `baseURL` changed from `'/'` to `''` which causes the page to refresh (at the same URL) instead of going back to the `rootURL`. In my app, this caused a weird behavior where `routeAfterAuthenticationOverride` was set on logout, which may send the user to the wrong URL if they immediately log back in. This was an unexpected bug that took a bit of time to figure out.

Unfortunately I don't have time to send over a PR right now, but as an end-user of ESA, my preference would be for ESA to throw an exception on app boot if it discovers that `baseURL` is undefined in `ENV`. In the future, it might be ideal to use `rootURL` instead, but I can't say I understand the full implications of the switch.

**Comment by lindyhopchris** [comment]
Is the `baseURL` ESA setting used for anything other than the redirect after signout? If not, I think it'd be less confusing if the setting was something like `urlAfterInvalidate` (not `routeAfterInvalidate`, as it's not necessarily an Ember route).

**Comment by marcoow** [comment]
Actually the `baseURL` should have been private from the beginning. It's not intended to be set anyway and should always just have the value that's configured for `rootURL` in `config/environment.js`.

**Comment by lindyhopchris** [comment]
ah ok, that clears up the confusion for me!
