### ISSUE TITLE
Better Documentation For Testing Authenticators

### ISSUE THREAD

**Issue by luketheobscure** [simplabs/ember-simple-auth#1052]
Just spent the better half of a day writing a simple test for my authenticators. It looks like in order to use the `authenticateSession` helpers, you have to register the desired authenticator as 'authenticator:test'. I don't see this documented anywhere, and I feel like this was unintentional. If there's a better way to do it, it should be documented.

FWIW, here's how I got the test working:

```coffeescript
`import { authenticateSession, currentSession } from '../helpers/ember-simple-auth'`
`import Ember from 'ember'`
`import { module, test } from 'qunit'`
`import startApp from '../helpers/start-app'`
`import FooAuthenticator from '../../authenticators/foo'`

module 'Acceptance: Authentication',
  beforeEach: ->
    @application = startApp()
    @application.register('authenticator:test', FooAuthenticator)

test 'Authenticate session', (assert) ->
  authenticateSession(@application)
  andThen =>
    expectedResults =
      authenticator: 'authenticator:test'
      userId: 1
      userName: 'Bobby Tables'
    assert.deepEqual currentSession(@application).get('data.authenticated'), expectedResults,
      'Authenticated session user data is correct.'
```

**Comment by marcoow** [comment]
`authenticateSession` is not for testing the authenticator but for acceptance tests in which you want to have an authenticated session. The `authenticator:test` authenticator is automatically registered by ESA in the test environment. You can pass any data you want to be available on the session directly to [`authenticateSession`](https://github.com/simplabs/ember-simple-auth#testing).

In order to test the authenticator you'd implement a unit test that directly calls `authenticate`, `restore` and `invalidate` on the authenticator instance and asserts on the results.

**Comment by luketheobscure** [comment]
It would still be nice to have this officially supported. My `authenticate` method has lots of touch points between adapters, models, and the store. Stubbing them out would make the test pretty worthless, so an acceptance test makes sense in this scenario.
