### ISSUE TITLE
need to refresh token from external event

### ISSUE THREAD

**Issue by shailendragnit** [simplabs/ember-simple-auth#1114]
I have to implement warning popup with message "session is going to expire after .. You want to extend" on click of yes button need to be refresh my token.
I am trying to invoke restore but not working because of private API.

**Comment by marcoow** [comment]
For showing such a warning you can simply rely on the expiration information in the session data (how that looks exactly depends on the authenticator you're using).

In order to manually refresh the token you can do sth. like (assuming the authenticator you're using has a `refreshAccessToken` method):

```js
// app/controllers/application.js
import Ember from 'ember';

const { inject: { service } } = Ember;

export default Ember.Controller.extend({
  session: service(),

  actions: {
   refreshToken() {
      if (this.get('session.isAuthenticated')) {
        let authenticator = this.get('session.authenticator');
       authenticator.refreshAccessToken(); 
      }
    }
  }
});
```

**Comment by shailendragnit** [comment]
@marcoow  Thanks. I am using custom authenticator. Getting undefined for this.get('session.authenticator')
