### ISSUE TITLE
Force restoring store

### ISSUE THREAD

**Issue by jcbvm** [simplabs/ember-simple-auth#1135]
This is more a question or feature request than a bug. Is there currently a (simple) way to force restore the session via the authenticator?

In my application I'm using the local store, but authentication happended elsewhere, so I when the application loads, I need the session to restore via the authenticator to make sure the local store gets in sync again. Currently this is not possible, because it will first lookup the local store where I'm not authenticated yet.

**Comment by marcoow** [comment]
No that's not possible and I don't think we'll expose the private restoration mechanism publicly as that would complicate things quite dramatically. Instead of hacking into the restoration mechanism you could simply write a custom authenticator though that reads the session info from somewhere and authenticates the session with it. See #1057 for a similar mechanism.
