### ISSUE TITLE
Make _secureCookies public ?

### ISSUE THREAD

**Issue by plcarmel** [simplabs/ember-simple-auth#1173]
I had to override `_secureCookies` so it always returns true:

```javascript
import CookieStore from 'ember-simple-auth/session-stores/cookie';

export default CookieStore.extend({

  _secureCookies: Ember.computed(function() {
    return true;
  })

});
```

I use https for my website. However, my fastboot instance uses http because it is located behind my server (response from fastboot are relayed by the server to the client browser).

**Comment by marcoow** [comment]
Actually your reverse proxy should set the [`X-Forwarded-Proto`](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields) header (or sth. similar) to identify the protocol of the original request as it came in from the browser. That should actually be picked up by FastBoot then I guess (if not I'd argue that should be fixed in FastBoot).

**Comment by plcarmel** [comment]
Thank you, I will look into that.
