### ISSUE TITLE
App does not build on 1.2.0 on node 0.12.x because of shorthand function syntax: Unexpected Token

### ISSUE THREAD

**Issue by kashiif** [simplabs/ember-simple-auth#1204]
#1186 changes `index.js` from
```
included: function(app) {
```

to
```
included(app) {
```

syntax. This breaks app on node 0.12.x (having `ember-simple-auth: ^1.1.0` in `package.json`) because of shorthand function syntax. 

I can send a pull request if the fix is desireable.

**Comment by marcoow** [comment]
@Turbo87: can you have a look? I guess we should have a Node 0.12 mode for the linter…

**Comment by Turbo87** [comment]
Node 0.12 LTS is unsupported by Ember CLI and Node itself since January and will likely break due to transitive dependency updates. This policy has been communicated widely for Ember CLI.

Technically bumping the Node version requirements is not a breaking change, but if you're building a low-level lib that is used as a transitive dependency you should still bump major. Since `ember-simple-auth` is not that low-level and can easily be pinned to a specific version (even easier with yarn, but then again yarn is Node 4+ too) I don't think we would necessarily need a major version bump here.

> I guess we should have a Node 0.12 mode for the linter…

That means we will have to revert to ESLint 2, because ESLint 3 is Node 4+. ESLint 2 however is unsupported at this point.

With all these tools that don't support Node 0.12 anymore I don't think it would be reasonable for us to support it either. The only choice to make here is if we should've bumped major. 🤷‍♂️
