### ISSUE TITLE
Allow for certain 401 responses to not invalidate session

### ISSUE THREAD

**Issue by Dhaulagiri** [simplabs/ember-simple-auth#1289]
We have a handful of cases where our API will return a 401 yet we _do not_ want this to invalidate the user's session.  We ascertain this based on information returned in the response's payload.  This is problematic with ESA because the logic [here](https://github.com/simplabs/ember-simple-auth/blob/a62fe97e6faddf29b716a95ecf45f466ca776bbc/addon/mixins/data-adapter-mixin.js#L123-L125) invalidates all sessions on a 401.

Is there some way to work around this constraint, or could someone suggest a way we might enhance this method to allow it to be more flexible here?

**Comment by marcoow** [comment]
You can just override the method in your adapter and add your logic in the overridden method.

**Comment by Dhaulagiri** [comment]
@marcoow I believe we looked into that but the override method would still need to call super which in turn runs though ESA's 401 logic we are trying to avoid

**Comment by marcoow** [comment]
You should not actually call `_super` if you don't want to have `_super`'s behavior.

**Comment by marcoow** [comment]
oops

**Comment by jmar910** [comment]
@marcoow Since the ESA adapter is mixed into our ApplicationAdapter, we specify some custom behavior in `handleResponse` then have to call super for the RESTAdapter's `handleResponse` to be called. I guess we really don't need to call `_super` but I dont know what the alternative is... ie... "Call `_super` but skip this mixins super"

**Comment by fivetanley** [comment]
The crux of the issue is that this method is named the same as the Ember Data method.

Let's take an example:

```javascript
// app/adapters/application.js

import Mixin from 'ember-simple-auth';
import DS from 'ember-data';

export default DS.RESTAdapter.extend(Mixin, {
  handleResponse(status, headers, payload) {
    const valid = myCustomLogic(status, headers, payload);
    if (valid) {
      // we want to call Ember Data's `_super` for `handleResponse`, but *not* Ember Simple Auth's super
     return this._super();
  }
});
```

Unfortunately, even if we override this method, `this._super` is still Ember Simple Auth's implementation. We can't skip the session invalidation. If we don't call `this._super`, we don't get the goodies that Ember Data or our base class provides to us.

If we moved the implementation of ESA's `handleResponse` to another method, we could allow for a bit more flexible customization when people override the Ember Data method named `handleResponse`:

```javascript
// ember simple auth implementation

export default Ember.Mixin.create({
  handleResponse(status, headers, payload) {
    this.validateResponse(status, headers, payload);
    this._super(); // call ember data's this._super! Or don't if you want to override it.
  },
  // the default implementation, but users of ESA can override if they wish!
  validateResponse(status, headers, payload) {
    if (status === 401 && this.get('session.isAuthorized')) {
      this.get('session').invalidate();
    }
  }
});
```

Then, if *I* wanted to override it to call `session.invalidate()` differently, I could override `validateResponse` instead or in addition to `handleResponse`.

@marcoow I think in general it might be useful to separate this logic from Ember Data's method names; it opens up for a bit more flexibility when subclassing. What do you think?

**Comment by marcoow** [comment]
Hadn't really though about the case that you'd want `_super` from e.g. `JSONAPIAdapter` but not `DataAdapterMixin` - makes sense of course.

@fivetanley: your proposal seems fine - if anyone feels like opening a PR that would be awesome ;)
