### ISSUE TITLE
Destroy cookie on logout

### ISSUE THREAD

**Issue by dbbk** [simplabs/ember-simple-auth#1322]
I'm using Cloudflare's [Bypass Cache on Cookie](https://blog.cloudflare.com/caching-anonymous-page-views/) feature to alter the caching behaviour of my app based on whether a user is logged in or out.

It all works fine until a user logs in for the first time, then logs out. When they logout, the cookie itself is not destroyed, but instead set to basically an empty object: `%7B%22authenticated%22%3A%7B%7D%7D`

Would it be possible to modify this behaviour to destroy the cookie entirely? I can only set Cloudflare rules for the existence of a cookie, not its contents.

Thanks

**Comment by marcoow** [comment]
Ember Simple Auth allows storing data in the session also when it is not authenticated. That requires the cookie to exist at all times.

**Comment by marcoow** [comment]
Avoiding cookies to be set in certain scenarios would require a major rewrite of the cookie store. In theory it should be possible to make the cookie's default value implicit in the sense that the code would simply assume that default value if the cookie isn't present rather than explicitly storing it in the cookie. Exploring this in a PR would be interesting but we won't have time to do that. We'd be happy to review a PR of course if you want to submit one.

I'm closing this for now - feel free to reopen if you'd like to contribute an implementation.
