### ISSUE TITLE
A way to use with Fastboot but not in Fastboot

### ISSUE THREAD

**Issue by The-Don-Himself** [simplabs/ember-simple-auth#1540]
I use Fastboot with Ember SimpleAuth but my use case is such that the Fastboot App Server will always render a page without authentication, in other words Ember SimpleAuth is only required for client side authentication. However, SimpleAuth generates a cookie when running under Fastboot, which messes up my caching. I use(d) Varnish to strip all cookies but I've just moved over to Fastly a Varnish powered CDN and had to learn and configured it to do the same. So I thought, maybe others are going through the same, and even if not, this really should be configurable in SimpleAuth.

I use the Adaptive Store, I once switched to the localStorage store which I believe would solve this issue but I switched back after reading it will affect authentication in private browsing mode on Safari and iOS Safari.

I propose to investigate how to make this configurable. If we add a disable in Fastboot boolean, how will that affect the service calls? Or do we add a setting say Fastboot user = cookie/null.

Not sure so opening this as an issue.

**Comment by marcoow** [comment]
Scenarios like this one are the reason why ESA was designed to be pluggable in the first place. You can simply implement your own session store and use that. I guess you would write something that uses `localStorage` (or a cookie or `sessionStorage`) in the browser and works like the [ephemeral store](http://ember-simple-auth.com/api/classes/EphemeralStore.html) in FastBoot. The store API is very simple - you only need to implement 3 methods really - check the [`BaseStore`'s API docs](http://ember-simple-auth.com/api/classes/BaseStore.html) for more info.

**Comment by The-Don-Himself** [comment]
Thanks for your response @marcoow , indeed a custom session store would be one way to solve this, but that means creating one in every project as well as keeping up with the API in case of changes. I find it simpler and more scalable to just use Varnish and strip all cookies coming from Simple-Auth, so that's what I use. But as I stated in the issue, perhaps there are others having the same issue but solving it in different ways. So I created the issue to investigate, if enough users reactive positively to it, whether to make it configurable in SimpleAuth itself.

**Comment by marcoow** [comment]
The idea behind ESA has always been to provide a library for implementing authentication/authorization solutions with little effort. The goal was to make it pluggable so that everyone can build custom solutions for specific requirements if need be but not necessarily support every use case out of the box in the core library. Everything that gets added makes the library gibber and more complex, which is something we're trying to avoid for the sake of ESA's long term sustainability.

So for anything that ESA does not support out of the box, the first question to ask is always: can that aspect be implemented via ESA's pluggable architecture easily? If the answer is yes that's great 👍 but that also makes it unlikely that the aspect in question will be added to the core library (unless it turns out to be something that the majority of the users are using which doesn't seem to be the case here). If you can solve the problem with using the adaptive store and stripping cookies in Varnish that's great and the solution is documented here now.

Implementing a custom session store is super easy though (I think - if that turns out to be wrong we need to make it easier or maybe better documented). The API is also very unlikely to change. In fact, there is no way it could change before a 2.0 release that's not even planned yet. And even if it would change with 2.0 we'd have to deprecate it first which we haven't done and have no intention to do. So while we will add deprecations over time and remove some things in 2.0, session stores aver very unlikely to be one of these things.

**Comment by The-Don-Himself** [comment]
Thanks for that comprehensive answer. I'm my free time, I try create a custom session store and report back  on its ease or difficulty. I'd even paste the method here incase others who come across this issue but can't go the varnish way. Thanks.
