### ISSUE TITLE
Make retry a replace instead of transition

### ISSUE THREAD

**Issue by jrock2004** [simplabs/ember-simple-auth#1663]
So one thing I have noticed that Ember Simple auth is using transition for your authentication methods. The problem this brings up is that if the user hits the back button after signing in, they are taken back to the sign in page even though they are still authenticated. Is there an easy way to change this to a replace? Maybe I need to override something? Thanks

https://github.com/simplabs/ember-simple-auth/blob/1.6.0/addon/mixins/application-route-mixin.js#L114

So this is the config in my environment.js file

```
'ember-simple-auth': {
  authenticationRoute: 'location.signin',
  routeAfterAuthentication: 'location.account'
},
```

Now if I add this new line

```
'ember-simple-auth': {
  authenticationRoute: 'location.signin',
  routeAfterAuthentication: 'location.account',
  routeIfAlreadyAuthenticated: 'location.account'
},
```

Now when I hit back, instead of the sign in screen, I am routed to `location.account`

**Comment by jrock2004** [comment]
Any update or thought on this? Seems really weird that after login and you hit back that its not taking you to the page you were before the sign in screen

**Comment by marcoow** [comment]
I think replacing the current route instead of transitioning might work indeed but I'm not sure how that would work with FastBoot and if there is an (or maybe several) edge cases in which that would not be as straight forward 🤔.

For now, you can use the [`UnauthenticatedRouteMixin` mixin](http://ember-simple-auth.com/api/classes/UnauthenticatedRouteMixin.html) in your signin route to make sure that route can only be accessed when the session is **not** authenticated.

**Comment by marcoow** [comment]
cleaning old issues
