### ISSUE TITLE
Acceptance Test Session Store Ember Simple Auth

### ISSUE THREAD

**Issue by jrock2004** [simplabs/ember-simple-auth#1685]
So I am trying to write an acceptance test for my ember app. I use Ember Simple Auth and in the route I have the following code

```
let session = getOwner(this).lookup('session:main'),
      sessionStore = this.get('session.store');

sessionStore.updateKey("my-app");
```

When I am running the app it works just fine. Now when I write the following test I get errors that `updateKey` is not a function

```
import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';
import setupMirage from 'ember-cli-mirage/test-support/setup-mirage';
import { currentSession } from 'ember-simple-auth/test-support';

module('Acceptance | service menu', function(hooks) {
  setupApplicationTest(hooks);
  setupMirage(hooks);

  test('visiting /service-menu', async function(assert) {
    this.server.createList('service-category', 5);
    this.server.create('location');

    currentSession(this.application);

    await visit('/location/testLocation/service-menu');

    await this.pauseTest();

    assert.equal(currentURL(), '/location/testLocation/service-menu');
  });
});
```

What am I missing? I do not want the user to be logged in.

**Comment by jrock2004** [comment]
Updating OP to give more information

**Comment by marcoow** [comment]
In the `test` environment, ESA automatically uses the [`EphemeralStore`](http://ember-simple-auth.com/api/classes/EphemeralStore.html) that only stores everything in memory. You should never directly update anything in the session store anyway though or if you do, trigger the store's [`sessionDataUpdated`](http://ember-simple-auth.com/api/classes/BaseStore.html#event_sessionDataUpdated) event afterwards so that the session becomes aware of the update.

**Comment by jrock2004** [comment]
@marcoow we do this as our site has multiple location so we need to separate sessions. Is there a better way?

**Comment by urHuckleberry1** [comment]
ESA
