### ISSUE TITLE
React to authentication in a component via modifier

### ISSUE THREAD

**Issue by hoIIer** [simplabs/ember-simple-auth#2361]
Would it be possible to create a modifier or some way to react to authentication change within a component?

e.g.
```
<div {{on "is-authenticated" this.updateStatus}}>{{status}}</div>
```

**Comment by BobrImperator** [comment]
I'm not sure this is a correct way to use modifiers, they are meant to provide functionality to a given element or based on it's lifecycle.

If you just need to do some conditional work based on your authentication status, then you should be able to just inject session service and use it's `isAuthenticated` property inside a template.

If you need to run some code when authentication succeeded, the session service exposes `authenticationSucceeded` and `invalidationSucceeded` events.

See the docs for the reference
https://ember-simple-auth.com/api/classes/SessionService.html

```js
// some-component.js
import Component from "@glimmer/component";
import { service } from "@ember/service";

export default class SomeComponent extends Component {
    @service session;
}
```

```hbs
// some-component.hbs

{{#if this.session.isAuthenticated}}
  Status OK
  
{{else}}
  
  Status Not OK
{{/if}}
```

Otherwise, if you'd like to have modifier semantics I'd recommend `did-update` from https://github.com/emberjs/ember-render-modifiers

Then in the template you'd be able to do this:

```hbs
<div {{did-update this.updateStatus isAuthenticated=this.session.isAuthenticated}}>
</div>
```

**Comment by hoIIer** [comment]
Ok thanks, I ended up realizing I could use isAuthenticated and had overthought the issue! Appreciate the feedback
