### ISSUE TITLE
ESA's Application route hides host app's route when using pod layout & embroider

### ISSUE THREAD

**Issue by vlascik** [simplabs/ember-simple-auth#2433]
ESA's empty application route in `app/routes/application.js` overrides host app's application route (`app/application/route`) when using embroider (somehow it doesn't in classic build). This obviously breaks the app when using pod layout.

I don't think ESA should provide files like these, this looks like a documentation issue, plus perhaps after https://github.com/simplabs/ember-simple-auth/pull/2318 ESA doesn't need an application route file anyway?

**Comment by BobrImperator** [comment]
Hello @vlascik 

ESA has implemented a way to strip away the file already, but it's not the default just yet as we're still supporting mixins until v5.

Please take a look at these guides https://github.com/simplabs/ember-simple-auth/blob/master/guides/upgrade-to-v4.md
Implementing this should fix your embroider issue and typescript.

I'm currently working on embroider support in ESA and I'd expect it to be included yet in v4 or already in v5.

**Comment by vlascik** [comment]
Hi @BobrImperator, yes I've seen it, I'm calling `this.session.setup()` in my application route already - the problem is, that in this specific scenario (pods + embroider), ESA's empty route file overrides my app's route file in the build output, and breaks the app.

Adding files to addon's `app` is probably not a good idea unless it's just a typical reexport, the ESA's empty route file probably doesn't belong there - the need for it either should only be mentioned in docs (which it already is), or the file should only be created in host app's directory via post-ember install `generate` command. However, this might be a breaking change and require a new major.

Not sure if I made the problem clear enough.

**Comment by BobrImperator** [comment]
@vlascik ESA will definitely remove the file as it was also reported that it caused problems with typescript.
The file was added in the ancient times for initializer works reliably when ESA was mounting a beforeModel hook on it.
This will be removed in V5 as I mentioned.

What you said is clear to me, but we can't remove this without a major release as you've mentioned.

I also asked if you're using the session method, because this file should already be stripped away during build and so it shouldn't cause anymore trouble - it fixed build issues for projects that use typescript and it's weird that it still breaks for embroider.

Could you make sure that you're configuring ESA inside your `ember-cli-build.js` so it removes the file?
https://github.com/simplabs/ember-simple-auth/blob/master/packages/test-app/ember-cli-build.js

**Comment by vlascik** [comment]
Oh, now I see what you mean, after I added `useSessionSetupMethod` to `ember-cli-build.js`, it worked fine.

Perhaps this should be mentioned in the readme, not just in migration guide? Didn't know about this step until you mentioned it.

Feel free to close this issue. Thanks.
