### ISSUE TITLE
Store data when not authenticated

### ISSUE THREAD

**Issue by tehmaestro** [simplabs/ember-simple-auth#383]
Hi and thank you for this library, it's pretty great. One question, how can I persist data across page reloads, when the user is not authenticated. I want to store some information, and take that information to the server only when the user decides to create an account and thus becoming authenticated.

Thanks.

**Comment by snovity** [comment]
@tehmaestro it seems that your solution with `invalidate()` call will still trigger a delete if your have two parallel anonymous sessions in two tabs. Say, if tab 1 updates anonymous session then tab 2 will delete everything and, in your case, will hit a back-end. 

I have the same problem as @tehmaestro and have an idea that maybe the best solution would be to have a configurable anonymous authenticator (not sure what would be the best name to call it). It would have only `restore` method and by default this method would do nothing. 

And it seems that this fix isn't that trivial, there are corner-cases and many parts of session are affected.

**Comment by snovity** [comment]
Also, maybe it would make sense to have a subkey on session called `anonymous` or something like that wouldn't be affected by authentications/invalidations. Just thinking out loud :) Would be interesting to hear what @marcoow thinks.

**Comment by marcoow** [comment]
I think the simplest fix would probably be to not clear the session when the authenticator's `restore` method returns a rejecting promise. Not sure whether this covers all edge cases though...

**Comment by tehmaestro** [comment]
Hey, one problem I noticed while further researching this, is that, when not authenticated, although you can use `this.set('session.something', something)`, using `this.get('session.something;)` does not work.
  Only when the session is authenticated, setting and getting stuff from localStorage works.

  I probably don't fully understand how Ember works, but I simply cannot find the lines of code that make the localStorage data available in the session object, when authenticated. I'm trying to modify the behavior so it fits my needs, but I just can't find it.
  Could you point me to the right direction? How and when does the data became available in the session object, like `this.get('session.data')` . Thank you.

**Comment by marcoow** [comment]
Yep. it uses `Ember.ObjectProxy` and the [`setUnknownProperty` method](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L279) to keep the store up to date.

**Comment by marcoow** [comment]
I thought about the topic and I think the fact that the session clears itself in certain situations war wrong from the beginning. The fact that the session's current content doesn't constitute an authenticated state doesn't require all of its content to be cleared. Yet, there's probably a simple solution for the problem:

As both the authenticator's `restore` and `invalidate` method receive the session's current content as an argument it would make sense to - if that session content doesn't constitute an authenticated state which is the authenticator's task to decide anyway - have the authenticator remove the security-relevant attributes from the session content (which would in most cases be the token and if not then the authenticator would know which attributes have to be removed, e.g. expiration times or refresh tokens in the case of the OAuth 2.0 authenticator), resolve or reject with that updated session content and in the session itself simply replace its content with whatever comes back from the authenticator and never completely clear itself (although it probably makes sense to have a method in the public API for that). That solution would have several advantages:

- the public API doesn't need to change
- no new concepts like anonymous authenticators etc. have to be introduced
- the session actually behaves like a real session in the way that it keeps data regardless of whether it's authenticated or not

There's 2 drawbacks that I would consider ok for a pre 1.0 release though:

- custom authenticators would potentially have to be changed so that they always resolve or reject with the updated session content and also delete relevant attributes from it in the `restore` and `invalidate` methods
- if data is persisted in the session that's relevant to security but the authenticator is unaware of that data would have to be deleted manually (in the `sessionInvalidationSucceeded` action if using the `ApplicationRouteMixin` or by handling the session's `sessionInvalidationSucceeded` event)

Would be great to get some opinions!

**Comment by tehmaestro** [comment]
I think this sounds really good.
  My personal case is:
   - the REST api is not stateless, because the API will be used only by my app. There are sessions and even cookies.
  - I allow users to access certain pages without creating an account. However, I do create a "guest" account in the backend, so I can monitor the actions and progress of the "guest" user.
 - Whenever he decides to create an account, I simply assign a username and password for him in the backend, and also, the frontend becomes authenticated.

  So that's why I needed a frontend unauthenticated state. I wanted to keep data in localStorage as I'm tracking the user in the not-authenticated, no-profile-created-yet state.

**Comment by marcoow** [comment]
I think the point is that the idea of the session is that it always exists regardless of whether it's authenticated or nor. Currently that's not the case though as as soon as you invalidate it all session data is lost (as it is when you reload the page without an authenticated session).

I'm not actually sure anymore though that the solution I suggest above is the way to go. The problem is that it moves the responsibility to decide which session attributes are actually security relevant and have to be deleted when the session is invalidated to the authenticator. The torii authenticatior e.g. though does not actually know which session attributes are security relevant as it only forwards these attributes from the torii provider. Also the solution makes the API for the authenticators more complex as they always need to resolve/reject with values, delete single properties from the data set etc.

A solution that uses a special session subway `secure` or so (similar to what @snovity suggests above) is probably simpler. Basically the idea would be to always leave the general session data (everything that's not in `secure`) untouched, never delete it etc. The only part of the session data that would be managed by the authenticators, deleted on invalidation etc. would be the `secure` subkey then. This makes the authenticator's API simpler and makes it easier to delete security-relevant keys on session invalidating (by simply deleting the complete subkey). I'll setup a 2nd pull request that implements this solution and see how this goes.

**Comment by tehmaestro** [comment]
Awesome. Thank you.
  I wanted to test it, but I was unable to get it working .. it works as before. Looking at the files, there is no "secure" mentions anywhere, so I'm guessing `npm install ember-cli-simple-auth` doesn't get this latest merge?

**Comment by marcoow** [comment]
No, `npm install ember-cli-simple-auth` installs the latest released version.

**Comment by tehmaestro** [comment]
I did a `bower install ember-simple-auth`, which reinstalled the bower packages, the version is indeed 0.7.3, but when searching for the keyword `secure`, in both the `simple-auth.js` and `simple-auth.amd.js`, there are no results.

**Comment by marcoow** [comment]
Yes, this is only on master for now. You cannot install this with npm or bower.
