### ISSUE TITLE
Local Storage Security Considerations

### ISSUE THREAD

**Issue by sebgie** [simplabs/ember-simple-auth#446]
I had a discussion about the security of storing session information in local storage recently. The concern is that if there is an XSS vulnerability in the app the session information can be read by an attacker quite easily.

Or as OWASP put it:

> Do not store session identifiers in local storage as the data is always accesible [sic] by JavaScript. Cookies can mitigate this risk using the httpOnly flag.

From https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Local_Storage

We use ember-simple-auth in combination with OAuth and I was wondering if there is anything that could be done to address that problem?

**Comment by marcoow** [comment]
That's a good point. I'd say this is mainly a matter of documentation as there's nothing that I'm aware of that could be done to somehow secure the `localStorage` store. The solution of course would be to use the cookie store instead.

Maybe the default store should be changed to be the cookie store actually...

**Comment by marcoow** [comment]
I thought about this again and actually there's nothing that could be done about this. Because Ember.js applications are JS apps and Ember Simple Auth is a JS library of course any store that's used to store the session in has to be accessible by JS anyway so even switching to the cookie store doesn't help here as the cookies has to be accessible by JS as well :smirk:.

So while I think the documentation should probably mention that you have to make sure the app isn't vulnerable to XSS, there's nothing that could be done about this.

**Comment by marcoow** [comment]
Closing this as there's no fix actually.

**Comment by roberkules** [comment]
@marcoow why does the cookie have to be accessible from JS? why can't ESA call an API to check whether the user is logged in or not (and that api call can also return the user's details)?

**Comment by marcoow** [comment]
ESA supports building something like this. The easiest way for doing so is to use cookie based authorization (as opposed to token based) where the API sets a cookie in the response if authentication was successful. That token would not be accessible by JS though but as the response was successful ESA would assume it to be present. ESA would still store its own authentication state (the fact whether the session is authenticated or not and if so which authenticator was used) in its own cookie or `localStorage` but that internal state would not contain any sensitive data.
