### ISSUE TITLE
Allow multiple Authorization headers with different names

### ISSUE THREAD

**Issue by ur5us** [simplabs/ember-simple-auth#448]
As far as I can tell, there's no official way to use Basic Auth + ESA as both rely on `Authorization: ...` headers. https://github.com/nickstenning/nginx-multiauth would be one way as a workaround but it's a bad idea for several reasons. Another way would be to allow a custom name for ESA authentication, e.g. `My-Custom-Authentication`. Right now I'd need to implement my own authenticator to be able to provide a custom name. Make it configurable?

**Comment by marcoow** [comment]
The OAuth 2.0 spec ([RFC 6749|(https://tools.ietf.org/html/rfc6749)) is specific about the header name so that shouldn't be changed or be configurable I'd say. With other mechanisms (e.g. the devise package) it would in theory be ok to make the header name configurable but I don't think it's worth it as it's pretty simple to [implement a custom authorizer](https://github.com/simplabs/ember-simple-auth#implementing-a-custom-authorizer) that uses a different header.

**Comment by ur5us** [comment]
I haven't read named spec but what you're saying basically means the spec doesn't allow for role based sessions, that is, having different sessions for admin + customer account at the same time, right? Also, using Basic Auth + OAuth2 is not a use case?

**Comment by marcoow** [comment]
Not sure what you mean with role based  session in this context but the bearer token spec says the header is `Authorization: Bearer ...`. Also it's really simple to implement a custom authorizer as explained above.

**Comment by ur5us** [comment]
By role based authentication I mean using different credentials for different parts of the app. Though I guess one would handle that case by case, potentially with a custom authorizer. Closing the issue though I don't see how one could easily use Basic Auth + OAuth2 at the same time. But that's more of a problem with the RFC I guess.
