### ISSUE TITLE
Add separate attributeName parameters for server-received values

### ISSUE THREAD

**Issue by johnmosesman** [simplabs/ember-simple-auth#455]
We have a Rails server using token-based authentication with Devise, but we cannot change the return from the session's controller. 

Since we can't modify the return from the server, and the parameters we're sending to Devise are already set (`token` and `email`), what do you think about adding extra options for parameters similar to `identificationAttributeName` and `tokenAttributeName`—for example, `serverIdentificationAttributeName` or `receivedIdentificationAttributeName`?

@ryanlabouve and I have enjoyed using simple auth, and we'd love to contribute with this feature if you think it's worthwhile.

**Comment by ryanlabouve** [comment]
Just to illustrate this issue, currently we authenticate (the server shows a `201`) and returns particularly named email and token parameters. Then there is a refresh which appears to be happening as a byproduct of setting the local storage keys with the the wrong property names. I have included a gif of this situation occurring.

![simple-auth-refresh](https://cloud.githubusercontent.com/assets/1318878/6499935/66662570-c2b8-11e4-8f8e-d084cce2654c.gif)

Thanks!

**Comment by marcoow** [comment]
I'm not sure why you're seeing that refresh but there's certainly something wrong as you're also not authenticated anymore after the refresh as the `localStorage` is empty then.

However, instead of adding more configuration attribute I think the better fix for this confusion is to simple change the `identificationAttributeName`'s default to `email` instead of `user_email`.

**Comment by marcoow** [comment]
#456 change the default of `identificationAttributeName` to `email` which should be sufficient - I don't want to add even more settings.
