### ISSUE TITLE
Don't advertize deprecated initializer functionality

### ISSUE THREAD

**Issue by zeppelin** [simplabs/ember-simple-auth#462]
Since the Ember container/registry separation, calling `lookup` in initializers is deprecated and [available only for backwards-compatibility](https://github.com/emberjs/ember.js/pull/9981), yet it's usage is still advertised in the [`ApplicationRouteMixin`'s documentation](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L36-L52). It would be good if an alternative solutuion was offered instead.

**Comment by vire** [comment]
@zeppelin could you submit a PR with an alternative solution? I'm very interested in this concept because I've used a lot of `container.lookup` in initializers.

Thanks!

**Comment by zeppelin** [comment]
@vire absolutely, but it'd be even better if we could get expert advice from @dgeb, he did the container/registry refactor.

**Comment by marcoow** [comment]
It would probably be god to use Ember's new [service injection API](file:///Users/marcoow/Library/Application%20Support/Dash/DocSets/EmberJS/EmberJS.docset/Contents/Resources/Documents/emberjs.com/api/classes/Ember.inject.html#method_service).

@dgeb: would that be the suggested way of making the session available, e.g.

```js
//app/components/my-component.js
export default Ember.Component.extend({
  session: authManager: Ember.inject.service('session')
})
```
?

**Comment by dgeb** [comment]
If you want to make a service available on a particular component, then you can definitely use the service injection API.

Note that: 

```
//app/components/my-component.js
export default Ember.Component.extend({
  session: Ember.inject.service('session')
});
```

Is equivalent to:


```
//app/components/my-component.js
export default Ember.Component.extend({
  session: Ember.inject.service()
});
```

This is because the property is named the same as the service (`session`).

You can certainly also call `application.inject()` from an initializer to make a service available more broadly (say, to all routes).

I've opened an RFC to steer the registry / container / initializer work in the direction I'd like to take it: https://github.com/emberjs/rfcs/pull/46

**Comment by marcoow** [comment]
Thanks @dgeb! Ember Simple Auth now uses the application's `register` and `inject` methods rather than the container's `register` and `injection`.

**Comment by dgeb** [comment]
Great - glad to help!
