### ISSUE TITLE
Devise - questions

### ISSUE THREAD

**Issue by ninja-** [simplabs/ember-simple-auth#468]
Looking at ember-simple-auth-devise, I am not exactly happy with using custom token authentication.
First - what is it exactly that requires simpleauth to use tokens instead of 'normal' devise behaviour?

These tokens are not even regenerated so that can lead to easy session fixation.

Devise for AngularJS has no need to use any custom tokens - https://github.com/cloudspace/angular_devise

Thanks for any help.

**Comment by ninja-** [comment]
That looks much better: https://github.com/kagemusha/ember-rails-devise-demo/blob/7efd3b537ef29207404ab219f9849d215285a2de/app/assets/javascripts/controllers/controllers.js.coffee

**Comment by marcoow** [comment]
https://github.com/cloudspace/angular_devise uses cookies which isn't really desirable for REST APIs where you want the API to be stateless. That's why everybody is using tokens for REST APIs. If you're not happy with that sth. else or implement a custom Ember Simple Auth authenticator/authorizer pair that uses cookies.

Closing this as it isn't actually an issue.

**Comment by ninja-** [comment]
ah I see - so that's the 'API key' kind of thing - well I can see the point now
I guess regenerating the 'API key' when user changes password would be enough
