### ISSUE TITLE
Trouble with AuthenticatedRouteMixin

### ISSUE THREAD

**Issue by somlor** [simplabs/ember-simple-auth#474]
Having trouble getting `AuthenticatedRouteMixin` to transition. (`UnauthenticatedRouteMixin` appears to be working fine.)

I created a very simple app to demonstrate:
https://github.com/somlor/simple_auth_demo

If you clone that app, then visit http://localhost:4200/user/1, this route should transition to login but is not.

Am I doing something wrong, or is this a bug?

Thanks,
Sean

**Comment by marcoow** [comment]
Are you sure you're not authenticated when visiting the route? Maybe you could setup a JSBin illustrating the problem.

**Comment by somlor** [comment]
Thanks, yeah, I have not even wired up the auth backend yet.

The problem is not just that the page is visible when it should not be. The problem is that when I add `AuthenticatedRouteMixin` the route renders nothing, and does not transition.

I could try to setup a JSBin if need be, but I did create the repo above specifically to demonstrate this issue. Figured it would be a better example since I'm using ember-cli.

Thanks,
Sean

**Comment by marcoow** [comment]
There are two problems in your code:

* you need to define the `user` route in `app/users/user.js` - that's because you're using a resource route (which I would advise against anyway as they only make things more complex and don't really add much value)
* you're not using the `ApplicationRouteMixin` which means that you would have to define the `authenticateSession` on the application route yourself. You would also need to manually handle the various session events.

**Comment by somlor** [comment]
@marcoow thanks so much. Your advice [solved my problem](https://github.com/somlor/simple_auth_demo/commit/dcb2622a385746c991eb4e03be9ed89b26c7dbd4). Sorry to trouble you with a non-bug. Really appreciate your help, and your work on this great lib!
