### ISSUE TITLE
Restore template

### ISSUE THREAD

**Issue by markr79** [simplabs/ember-simple-auth#486]
I can't find a way to show any template like "Connecting to server..." while session is being restored. It seems that library waits for restore promise to be resolved before rendering anything, but it may take some time to reauthenticate. Any suggestions?

**Comment by marcoow** [comment]
In the majority of cases there is no server connection for session restoration. Which authenticator are you using?

**Comment by markr79** [comment]
I have a custom one that authenticates against xmpp server where you need to exchange some messages with the server to restore a session.

**Comment by marcoow** [comment]
For the restoration that happens when the application initializes that should actually be handled by the [application's loading route](http://guides.emberjs.com/v1.11.0/routing/loading-and-error-substates/) already.

The restoration that happens when the session changes in another tab should not modify the UI anyway as it should be invisible to the user and only change the session's content or when the session is invalidated log the user out.

**Comment by markr79** [comment]
@marcoow I see your point. I will close the ticket for now and will reopen if I could confirm that the issue is in the library.
