### ISSUE TITLE
Ember simple auth redirects user back to index page after logging in on safari

### ISSUE THREAD

**Issue by ohcibi** [simplabs/ember-simple-auth#505]
Consider this example: https://github.com/ohcibi/ember-simple-auth-safari-bug

It works fine in chrome and firefox but in safari, the app redirects back to the index route after the user has logged in.

**Comment by marcoow** [comment]
Not sure what the actual problem is. Steps I'm taking:

* go to http://localhost:4567
* I'm redirected to http://localhost:4567/login as I'm not authenticated
* I log in
* I'm redirected back to http://localhost:4567 as the `index` route is the default config value for [`SimpleAuth.Configuration.routeAfterAuthentication`](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/configuration.js#L53)

Also this is consistent for Chrome as well as Safari

**Comment by ohcibi** [comment]
NVM. I don't know why but after restarting Safari it all worked. I tried to disable all plugins and closed tabs but I didn't restarted the whole browser until after I posted this. Sorry for bothering...
