### ISSUE TITLE
Custom fields in resolve object of custom authenticator not set in session

### ISSUE THREAD

**Issue by sarus** [simplabs/ember-simple-auth#516]
I'm working on a new project now and in my previous project using ESA `~0.3` (I know i know it's old haha) I was able to "inject" additional values into the session as part of my custom authenticator by adding them to the object returned from resolve.  The code looked like this:

```javascript
  authenticate: function(options) {
    var self = this;
    return new Ember.RSVP.Promise(function(resolve, reject) {
      var data = { identification: options.identification, password: options.password };
      self.makeAuthenticationRequest(data).then(function(response) {
        Ember.run(function() {
          resolve({
            isAuthenticated: response.isAuthenticated,
            isAdmin: response.user.is_admin,
            id: response.user.id,
            sessionID: response.sessionID
          });
        });
      }, function(error) {
        var response = JSON.parse(error.jqXHR.responseText);
        Ember.run(function() {
          reject(response.userMessage);
        });
      });
    });
  }
```

My new project does the exact same thing but I'm now using ESA `0.8-beta2` with ember-cli and the session is not modified with the additional values (tested by simply printing out the session object in the init method of the application controller).  The `isAuthenticated` value is there and the authentication works great, just no custom fields in the session.

Based on the documentation and examples it looks like adding values to the resolved object in the custom authenticator should work.  Is this still the correct way to add values to the session object at authentication time?

Thank you!

**Comment by marcoow** [comment]
Anything that the authenticator's `authenticate` method resovles with is still accessible via the session but has been moved to the `secure` key, so instead of `this.get(session.value)` you would now do `this.get(session.secure.value)` instead.

Also you shouldn't try to set the `isAuthenticated` property from the object the authenticator is resolving with. The session's `isAuthenticated` property is set to true automatically when the promise returned by the authenticator's `authenticate` method resolves, and to false if it rejects.

**Comment by sarus** [comment]
@marcoow thank you for the response.  Greatly appreciate it!
