### ISSUE TITLE
Devise seems very generic but then used for a specific library?

### ISSUE THREAD

**Issue by robclancy** [simplabs/ember-simple-auth#565]
Why not just make the devise provider something like an `api` provider? (or better name I can't name things).

I don't use devise but it is very close to my needs so I will copy it. It already has a lot of setting so already seems like a very generic custom provider. The only issue I have is with https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/lib/simple-auth-devise/authenticators/devise.js#L131 not sending the status code.

If you changed that line to give the status code in the reject and changed defaults to be using RESTful urls you would essentially have a rest adapter. When I first started trying this out I expected this to just be the default with better providers being the extensions.

Just seems weird to me so thought I would bring it up, going to roll the custom one but would be nice if I could just use the officially support one. Even if you just made that `status` change I would be able to use the devise adapter instead.

**Comment by marcoow** [comment]
The devise authenticator/authorizer are really specifically built for Devise. You might want to look at [jpadilla/ember-cli-simple-auth-token](https://github.com/jpadilla/ember-cli-simple-auth-token) for a more generic solution.

**Comment by robclancy** [comment]
I know what it is built for, that doesn't change the fact it is very generic in itself and officially supported. One little change and it could be used for anything.

**Comment by marcoow** [comment]
"Officially" supporting other types of backends with the devise package would also mean supporting those, thus making Devise specific changes impossible. Also I don't like the idea that the "Devise" authenticator is the one that's intended to be the generic one actually.

I'd be happy with to merge a PR though that extracts a generic authenticator and authorizer from the Devise ones and extends the Devise authenticator and authorizer from these then.

**Comment by robclancy** [comment]
Wouldn't it make more sense to have a generic one that devise extended? Is
everything covered in tests (can't check right now)? I will be making a
more generic one tomorrow most likely and if it works out will look to see
if it is good enough to PR in.

**Comment by marcoow** [comment]
Yes, devise should extend the generic one - that's what I meant. Be sure to base a PR on the ember-cli-addon branch.

**Comment by juni0r** [comment]
I second the idea to at least rename the Devise authenticator / authorizer. I built a Rails backend for my client app and assumed that the Devise authenticator would work with Devise out of the box. This isn't the case at all and created a lot of confusion.

I ended up having to customize so many things on the server side since Devise doesn't support _anything_ that Simple Auth does on the client side. Token auth isn't even part of Devise anymore. Even [the gist](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6) referred to in the authorizer docs doesn't work with header-based authorization but instead uses url parameters.

As I see it, associating this authentication method with the Devise gem doesn't make any sense at all. I ended up throwing out Devise completely since it didn't provide _any_ useful functionality only adding an unneeded dependency.
