### ISSUE TITLE
Feature: block all routes by default

### ISSUE THREAD

**Issue by knownasilya** [simplabs/ember-simple-auth#567]
So being explicit in which routes to unblock, instead of vice-versa. This is better for security, because it's better to ship a blocked route, then an open one when it should be blocked.

Maybe having an option that toggles between the two modes.

**Comment by marcoow** [comment]
Requiring authentication for a route isn't really about security at all as you're always able to see the source of the blocked page etc. Also you could make all the requests to the backend etc. and the server needs to make sure it doesn't respond with anything that's not accessible without being authenticated. Requiring authentication for a route is instead only a UI feature.

Also making all routes requiring authentication would be implicit instead of explicit which adds complexity as you don't see what's going on as good. The much better solution for this is to add an `internal` route and then have all the parts of the application that are only visible for authenticated users under that base route:

```js
Router.map(function() {
  this.route('login');
  this.route('internal', function() {
    this.route('feature-a');
    …
  });
});
```

**Comment by kottenator** [comment]
Hi! I'm also seeking for this feature - to block all routes in one place.
The `internal` route you suggest to use is not actually a route but some kind of container. 
But extra mappings will be created for template, route, controller, etc.
And also all child route names will start from `internal.*` so I will have to _reset namespacing_ for all child routes...

**Comment by knownasilya** [comment]
And change the path, so that you don't have `/internal/*`.. which is unacceptable if the app is already at something like `/dashboard`

**Comment by marcoow** [comment]
If you need a solution that works withouh an `internal` route refer to the wiki for a solution: https://github.com/simplabs/ember-simple-auth/wiki/Recipe:-Defaulting-to-Authentication-Required-Routes

**Comment by knownasilya** [comment]
:+1: Thanks for the workaround.
