### ISSUE TITLE
Import error on ff-abrams

### ISSUE THREAD

**Issue by Libermentix** [simplabs/ember-simple-auth#603]
First of all, great work on getting the Addon to support services and Ember 2.0 :+1: 

Now that I have tried out the beta (i.e. the ff-abrams branch) I'm running into import errors for our third party authenticator (https://github.com/jpadilla/ember-cli-simple-auth-token):

```
Error: Could not find module `simple-auth/authenticators/base` imported from `simple-auth-token/authenticators/token`
```
I realized, that you are now referring to the package as 'ember-simple-auth' in index.js, so after changing simple-auth to ember-simple-auth, everything went fine.

My question though: is this renaming intended (so should i send a PR to the 3rd party lib) or was this unintentional? Or is my approach generally wrong?

**Comment by marcoow** [comment]
This is intentional. While not actually necessary, using the Addon name as the base module is the default and actually makes sense anyway. Given that 1.0 will include quite a lot of breaking changes anyway I'd say adding another one with renamed modules shouldn't be a big problem (as it's also easel fixed).
