### ISSUE TITLE
ESA redirects to last logged in page after invalidating session and then logging in again

### ISSUE THREAD

**Issue by sarus** [simplabs/ember-simple-auth#638]
I'm probably forgetting to clear something but here is what is happening after upgrading to ESA 1.0 (jj-abrams)

1. Admin user logs in and manually navigates to an admin only page
2. Admin user logs out while on the admin only page
3. Site redirects back to login page
4. New, non-admin user logs in and is redirected to the last page the admin user was on (which the new non-admin user can't access and thus is redirected to a page not found page)

I copied over my old `environment.js` configs:

```
    base: {
      store: 'session-store:local-storage',
      authenticationRoute: 'signin',
      routeAfterAuthentication: 'index', //<-- Does this still work?
      routeAfterInvalidation: 'signin',
      authorizer: 'authorizer:hamachi',
      session: 'session:hamachi'
    }
```

I don't think this happened pre 1.0 so I'm thinking maybe the `routeAfterAuthentication` isn't set properly by which I mean I'm not setting it correctly.

Is there a way to clear the last logged in page so a new user logging in doesn't get redirected back to the previous page that was logged out from?

Thanks!

**Comment by marcoow** [comment]
Please provide your `routes/application.js` as well.

**Comment by sarus** [comment]
`routes/application.js` is pretty much empty:

```
import Ember from "ember";

import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
});
```

**Comment by marcoow** [comment]
ah, I think I know what the problem is - ESA will reload after logout so that when you logout on an admin-only page that route will be reloaded so that when the app starts again it will start on that route which redirects to login as it is an authenticated route and the login page will redirect to the previous page after login (which isn't accessible then because of lacking permissions).

**Comment by sarus** [comment]
Interesting.  Is this a normal Ember behavior or something that can be tweaked in ESA?  Where is Ember remembering what the previous route was (for a different user)?  On a logout the entire page is refreshed back to the login screen (or it appears to be) so I assumed any state from the previous logged in user would be lost.

Ah okay, I did a quick test and if after logging out of the admin account I manually refresh the page (clicking on the browsers refresh button) then the new user is not redirected to the last page that was logged into by another user.

Is there a place where I can modify this behavior or clear out the last remember route?

**Comment by marcoow** [comment]
There is no code that remembers the last route but when you log out [ESA reloads the current location](https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/addon/mixins/application-route-mixin.js#L100) so when after the reload the Ember app restarts it will restart at the same route you clicked "logout" on (in your case that page would redirect to the `login` page which will redirect back to the previous page after successful login).

What you'd want to do is instead of reloading the current location on logout redirect to the start page of your app.
