### ISSUE TITLE
Default application.js route breaks build, when ember-cli-coffeescript used

### ISSUE THREAD

**Issue by youroff** [simplabs/ember-simple-auth#659]
So application doesn't build when `application` route written in coffee. I know I can just use JS for that particular file, but is there a prettier solution?

**Comment by marcoow** [comment]
Please add info on the exact error you're seeing, ideally a demo project that shows the error.

**Comment by youroff** [comment]
Please refer here: https://github.com/kimroen/ember-cli-coffeescript/issues/92

Demo project would be exactly like your dummy app but with Coffescript (at least application route should be written in coffee). So I found workaround to code that particular route in JS, but may be there are better options.

**Comment by marcoow** [comment]
Seems like kimroen/ember-cli-coffeescript doesn't really work with Ember CLI's way of having addons merge stuff into the application.

**Comment by bkCDL** [comment]
For those who can't convert their entire ember app from coffeescript to ES2015 right away, I found that if merely my application route is javascript instead of coffeescript  (/routes/application.js instead of /routes/application.coffee), it works for the time being. Of course, this is a transitional step and not a long-term suggestion.

**Comment by erichonkanen** [comment]
> For those who can't convert their entire ember app from coffeescript to ES2015 right away

Or for those you don't want to convert their app to es2015 at all!
