### ISSUE TITLE
v1.0: Hook point for initializing session from query parameters?

### ISSUE THREAD

**Issue by thedeeno** [simplabs/ember-simple-auth#665]
If my app launches with a url like: `myapp.com?token=hgajas` what's the most appropriate simple-auth hook point to initialize my session with the data in this query string?

More concretely, if a remote gateway redirects to my site with a JWT in its payload, how do I use it? Would I leverage `session.set` at initialization time? Should I make a custom `store` that checks the current url before restoring from, say, localStorage? What feels right to those more experienced?

I'm concerned about spinning my wheels by hooking in too early or too late in the normal lifecycle.

**Comment by marcoow** [comment]
You just implement a custom authenticator that authenticates the session with the data read from the query string.

You should never try to set the session authenticated or edit anything in the session store directly - you have to use the session's `authenticate` method to authenticate the session but can of course pass a custom authenticator to that.

**Comment by thedeeno** [comment]
@marcoow Thanks for getting back. Ok, so you'd manually use the custom authenticator in your application route's `beforeModel` hook?

**Comment by marcoow** [comment]
exactly

**Comment by thedeeno** [comment]
money. thanks.

**Comment by thegranddesign** [comment]
@marcoow so my case is similar, but not the same.  In my case I'm using a JWT, so since it's self-contained, I don't really want to attempt an authentication when I land on a route that's using the `token` query param.

What I want is to just be able to say "Hey ember-simple-auth, here's a token.  So the next time you send session data to `authorize`, use this."  Once it's in the store, and it sends it to the endpoint, the endpoint will blow up if it's invalid and the normal flow can take over.

**Comment by marcoow** [comment]
@thegranddesign: you still have to use a custom authenticator for that. Of course that could resolve immediately with the JWT that you already have.
