### ISSUE TITLE
Feature request: sessionRestored

### ISSUE THREAD

**Issue by jcbvm** [simplabs/ember-simple-auth#686]
I'm running jj-abrams succesfully, but I'm currently missing a callback on the application route for when a session got restored, because I'd like to do some stuff when a session gets restored. Maybe it's an idea to add a 'sessionRestored' method on the ApplicationRouteMixin which is similar to 'sessionAuthenticated' and 'sessionInvalidated'.

**Comment by marcoow** [comment]
This is actually not so easy as has been discussed here several times already. With jj-abrams though when the session is restored successfully on application startup it will already be fully authenticated when the application route's `beforeModel` hook resolves.

**Comment by jcbvm** [comment]
So for `jj-abrams` the following would work?

    // application-route-mixin
    beforeModel() {
        if (this.get('session.isAuthenticated') {
            this.sessionRestored();
        }
        return this._super(...arguments);
    },
    sessionRestored() {
        // overwrite if needed
    }

Or are there some other place which can trigger a restore?

**Comment by marcoow** [comment]
You must call `_super` first as the application route's `beforeModel` method that ESA implements actually does the session restoration:

```js
beforeModel() {
  return this._super(...arguments).then(() => {
    if (this.get('session.isAuthenticated') {
      // session is restored and authenticated
    }
  });
}
```

The other situation when a session will get restored is when you have 2 tabs or windows of the same app open and log in in one of them. In that case the session will be restored in the other tab or window. If you want to handle that as well you have to override the `sessionAuthenticated` method.

**Comment by davekaro** [comment]
I am curious since I had similar goals, but when I tried to call `then` from super I got `Error while processing route: index this._super.apply(...).then is not a function TypeError: this._super.apply(...).then is not a function`. This would make sense if `this._super()` didn't return a promise, but from what I can tell https://github.com/simplabs/ember-simple-auth/blob/master/addon/instance-initializers/setup-session-restoration.js#L12 it does. What am I missing?

**Comment by davekaro** [comment]
Ok I figured out what was going on. Since https://github.com/simplabs/ember-simple-auth/blob/master/addon/instance-initializers/setup-session-restoration.js#L12 overrides `beforeModel` but then ends up calling the original `beforeModel` after session is restored, there is no need to call `this._super()` in the application route `beforeModel`. Or, if you do, the returned value is not what is returned in `setup-session-restoration.js`.

**Comment by thatikuntap** [comment]
I am trying to restore session when browser is refreshed
 i.e. window.location.reload(true) is not restoring session.
I am not sure relates to this discussion

**Comment by thatikuntap** [comment]
restore session is working after window refresh., beforeModel hook was the issue

**Comment by marcoow** [comment]
@jcbvm, @davekaro: is this still relevant? See the dummy app for a new pattern for handling the case when the session was successfully restored or authenticated from another tab (which works via restoration as well): https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/routes/application.js. This pattern will probably be merged into the library at some point.

**Comment by davekaro** [comment]
As far as I know this issue is no longer relevant.

**Comment by jcbvm** [comment]
I think its ok to close this issue indeed.
