### ISSUE TITLE
Possible to have pods-like structure for authenticators and authorizers?

### ISSUE THREAD

**Issue by bttf** [simplabs/ember-simple-auth#697]
For example, instead of:

`app/authenticators/oauth2.js`
`app/authorizers/oauth2.js`

Follow a 'pods-like' structure:

`app/oauth2/authenticator.js`
`app/oauth2/authorizer.js`

We could see this cleaning up the file structure of our app a little bit.

**Comment by marcoow** [comment]
That should work - I guess you just have to reference the authenticator as `oauth2:authenticator` instead of `aithenticator:oauth2` then and analogously for the aithorizer.

**Comment by bttf** [comment]
Tried it, did not work exactly as planned ... Attached is output of resolver after making the changes mentioned above
<img width="1421" alt="screenshot 2015-10-05 22 30 43" src="https://cloud.githubusercontent.com/assets/2374625/10300857/ed71baa6-6bb0-11e5-88b6-2135f85d7867.png">

**Comment by marcoow** [comment]
You can check the "Container" tab in the Ember Inspector to find out what identifier the authenticator was registered for (if at all).

**Comment by bttf** [comment]
They aren't registered in the container when stored in pods-style directories.

**Comment by marcoow** [comment]
Doesn't seem to be supported by Ember CLI then.

**Comment by aricallen** [comment]
In case anyone was also looking into this, I verified that it is in fact possible to use a pod style structure for you're authenticator/authorizer. I successfully kept both of them in an 'oauth2' folder and have a working app that uses both. I tried what @marcoow suggested first and referenced them with `oauth2:authenticator` but that was returning an `unknown mixin` error message. So I tried the traditional way as `authenticator:oauth2` and everything worked fine. Not sure if this is due to an Ember CLI update or not but wanted to share my findings. 

![screen shot 2016-06-15 at 9 52 55 am](https://cloud.githubusercontent.com/assets/5804876/16089216/f60c7e3a-32de-11e6-995d-4dd40a62393c.png)

![screen shot 2016-06-15 at 9 56 56 am](https://cloud.githubusercontent.com/assets/5804876/16089372/96f4d0ea-32df-11e6-8c18-5922829a8962.png)

**Comment by marcoow** [comment]
@aricallen: nice but actually [__pods are dead__](https://twitter.com/ebryn/status/733161408091721728) and I wouldn't recommend anyone using them right now.

Ember Simple Auth will definitely support the [unified module system](https://github.com/emberjs/rfcs/pull/143) once that's available.
