### ISSUE TITLE
Allow to turn off redirection after sign in / sign out

### ISSUE THREAD

**Issue by Fryie** [simplabs/ember-simple-auth#802]
Currently, if you mix in the ApplicationRouteMixin and do not override the sessionAuthenticated / sessionInvalidated hooks, every authentication / deauthentication will trigger a page load. In some cases, this is undesirable, e.g. if sign in is part of a larger, explicitly managed process.

Overriding the hooks is an option if you *always* want to manage the process yourself. However, in my case, I like the default behaviour - keeping track of which site the user wanted to visit originally - except for a few cases.

Currently, my solution consists in wrapping the call via a method on a service, setting a property on that service depending on whether the `refresh` argument was set to true, and then checking that property in the e.g. `sessionAuthenticated` hook to decide whether to call `this._super()` or not. However, that seems somewhat dirty.

One option would be to allow to pass options to the `authenticate` method on the session. Another idea would be to extract the behaviour of redirecting to the originally requested page into something that can easily be called from a custom hook. Maybe both would make sense?

**Comment by marcoow** [comment]
Actually authentication should never trigger a page load but only a transition to the `routeAfterAuthentication`. Session authentication will always trigger a reload and you should be aware that that's also a security feature as it clears out all state from memory, e.g. Ember Data models that the user shouldn't have access to unless authenticated.

Also the only reason to mixin the `ApplicationRouteMixin` is to get that automatic session events handling. If you don't want that you can just not mixin the mixin - it's not really required for the library to load. If you only want the default behavior to apply in some cases it's perfectly fine to override the methods and only call `super()` when you want the default behavior to be applied.

**Comment by Fryie** [comment]
> If you only want the default behavior to apply in some cases it's perfectly fine to override the methods and only call super() when you want the default behavior to be applied.
Sure, the problem is that the hooks don't get passed any arguments. I can use it by wrapping everything into a service and setting properties on it, but it's slightly risky, since I might accidentally not use the wrapper at some time and then the behaviour is inconsistent (depending on what state the property was last in).

>  If you only want the default behavior to apply in some cases it's perfectly fine to override the methods and only call super() when you want the default behavior to be applied.
Yes, although there are some issues in Ember with _super() and async actions. And testing would be much easier too, if one could call a method instead of using inheritance.

**Comment by marcoow** [comment]
Not sure what your use case is. Can you elaborate a bit more?

**Comment by Fryie** [comment]
Okay, sure.

Normally, when a user signs in through the normal sign in page I want to follow the default behaviour (keep track of where the user wanted to go and transition to that route or a default route instead). However, when the user signs up, I also sign him in and in this case I want to transition to a special "onboarding" route.

Here's how I currently do it:
```{javascript}
// app/services/auth.js
signIn(email, password, { redirect } = { redirect: true }) {
    this.set('redirectAfterSignIn', redirect);
    return this.get('session').authenticate('authenticator:application', email, password);
  }

// app/routes/application.js
export default Ember.Route.extend(ApplicationRouteMixin, {
  sessionAuthenticated() {
    // this is somewhat hackish
    // the problem is that 'this._super()' does not work with async, see:
    // https://github.com/emberjs/ember.js/issues/4632#issuecomment-120581786
    var mixin = ApplicationRouteMixin.mixins[0];

    this.get('auth').setCurrentUser().then(() => {
      if (this.get('auth.redirectAfterSignIn')) {
        mixin.properties.sessionAuthenticated.call(this);
      }
    });
  },
```

Now the problem is that I kind of depend on the fact that `session.authenticate()` is never called directly, but only indirectly, because otherwise the value of `auth.redirectAfterSignIn` is unspecified (could be anything). It's kind of easy to make a mistake here. It would be kind of handier to be able to pass some options to `authenticate` (ditto invalidate) that you can then access in the `sessionAuthenticated` hook.

Extracting the redirection behaviour into a callable method would also be nice to have, but it's not as important.

**Comment by marcoow** [comment]
You cannot pass arguments to `Session.invalidate` that would then be available later on. All arguments that you pass are forwarded to the authenticator.

I'm not sure what you mean with 

> Now the problem is that I kind of depend on the fact that session.authenticate() is never called directly, but only indirectly

I think your solution works well actually, the only thing that makes it complex is the fact that you're loading the current user in the `sessionAuthenticated` method. Instead of doing that I'd suggest to do that in the `model` method of your application's `internal` or whatever you're using section that you redirect the user to after signin or signup. That way you would also be able to show a loading route while loading the current user. Alternatively you could use a service that exposes a CP that returns the current user as in the dummy app - in that case you'd have to deal with the fact that that CP returns a promise though. In any case, if you don't do anything async in the `sessionAuthenticated` method (which I'd say you shouldn't) you can just call `super()`.

**Comment by Fryie** [comment]
> I think your solution works well actually

It works, as long as I always go through the `auth.signIn` method. The moment I - or another developer - inadvertently call `session.authenticate()` directly, its transitioning behaviour will completely depend on what the last call was.

> Instead of doing that I'd suggest to do that in the model method of your application's internal or whatever you're using section that you redirect the user to after signin or signup.

This doesn't work if you need the user information to be available outside of the `internal` part, too, *if the user is signed in*. Think about some information about the user that you would like to display, if he is signed in.

> Alternatively you could use a service that exposes a CP that returns the current user as in the dummy app

I'll have a look at the dummy app. However, CP and Promises are not always easy to handle, in my experience...

**Comment by marcoow** [comment]
> This doesn't work if you need the user information to be available outside of the internal part, too, if the user is signed in. Think about some information about the user that you would like to display, if he is signed in, like "you have 5 credits available" or something.

True, I'm actually thinking about a better way to handle that but it's not so easy unfortunately.

**Comment by karellm** [comment]
@marcoow I will add my use case here too since it is related.

1/ User signs up, it returns a session that we authenticate the user with. Also sends a confirmation email to the user, inviting him to set his password
2/ The user clicks the link in the mail (still authenticated at this point) and set his password. For security reasons, every time a password is changed, we kill all associated sessions of the user. So we need to invalidate the session and since the user just entered the password, we'd like to seemlessly reauthenticate him.

Right now, when we invalidate the user, it always triggers a redirect, even if we call `finally()` on the promise returned by `invalidate()`. Does that use case make sense? Do you have a suggestion how to kill the redirection in that scenario?

**Comment by marcoow** [comment]
The `invalidate` method doesn't take any arguments. It passes the current session data to the authenticator as that might need it to invalidate it on the server side etc.

The problem here is that the `ApplicationRouteMixin`'s `sessionInvalidated` method might get called in 2 scenarios:

* you're calling `this.get('session').invalidate()` somewhere
* the session data changes externally (e.g. because the user logged out in another tab) which causes the session to invalidate itself

You cannot really distinguish between the 2 cases in the `sessionInvalidated` method.

**Comment by karellm** [comment]
I understand that and I use the data from the session in our code. That's all good.

When I want to invalidate the session manually though, I call `this.get('session').invalidate();`. This does not take any arguments at the moment. Why couldn't we pass options?

1. Call `this.get('session').invalidate({skipTrigger: true});`
2. Which call [this](https://github.com/simplabs/ember-simple-auth/blob/master/addon/services/session.js#L200). Nothing as to change really since it already passes the arguments.
3. Which call [this](https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L31). The arguments are lost at this point. But we could now do something like:

```js
  invalidate(options) {
    options = options || {};                               // OPTIONS PASSED
    Ember.assert('Session#invalidate requires the session to be authenticated!', this.get('isAuthenticated'));
    return new Ember.RSVP.Promise((resolve, reject) => {
      let authenticator = getOwner(this).lookup(this.authenticator);
      authenticator.invalidate(this.content.authenticated).then(() => {
        authenticator.off('sessionDataUpdated');
        this._clear(!!options.skipTrigger);                                     // THE IMPORTANT CHANGE
        resolve();
      }, (error) => {
        this.trigger('sessionInvalidationFailed', error);
        reject(error);
      });
    });
  },
```

**Comment by karellm** [comment]
@marcoow Does my suggestion make sense? Right now I'm stuck with implementing a way to invalidate a session and create a new one right after that.

**Comment by marcoow** [comment]
@karellm: I wouldn't want to add sth. like that as it's only needed for ony very specific use case. Also the argument doesn't affect session invalidation itself at all but is just used to pass a value on that you need later.

You could just as well set a property in the session data that you check later on, e.g.

```js
this.get('session').set('data.skip');
this.get('session').invalidate();

// later on
if (this.get('session.data.skip')) {
  // …
}
```

**Comment by karellm** [comment]
@marcoow I understand you don't want to add this to the API. I have implemented the solution you mentioned. For future reference:

```js
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  sessionInvalidated() {
    if (this.get('session.skipRedirectOnInvalidation')) {
      this.set('session.skipRedirectOnInvalidation', false);
    }
    else {
      this._super(...arguments);
    }
  }
});
```

And wherever you want to invalidate and reauthenticate:

```js
const session = this.get('session');
session.set('skipRedirectOnInvalidation', true);
session.invalidate().then(() => {
  session.authenticate('authenticator:application', {email, password});
});
```
