### ISSUE TITLE
Make offset for token refresh a config property

### ISSUE THREAD

**Issue by bakerac4** [simplabs/ember-simple-auth#823]
In _scheduleAccessTokenRefresh for the OAuth 2 Password Grant Authenticator we schedule based on 
`const offset = (Math.floor(Math.random() * 5) + 5) * 1000; `
(along with expiresAt,  and now). Id like to be able to overwrite the offset with a config property. 

If you have a slow connection and you make a call to refresh the token but the server doesn't process it in time (or receive it in time), the server will check and the token that you sent up is now expired so the refresh will fail.

**Comment by marcoow** [comment]
Sounds like a good idea - PR that adds that would be cool!

**Comment by Charizard** [comment]
I was thinking about this and was wondering how the `offset` config would look like in `conifg/environment.js` file.

Should it be placed in root level?
```javascript
ENV['ember-simple-auth'] = {
  authenticationRoute: 'signin',
  offset: 12 #in seconds?
};
```
Should it be placed within the `oAuth2PasswordGrantAuthenticator` key?
```javascript
ENV['ember-simple-auth'] = {
  authenticationRoute: 'signin',
  oAuth2PasswordGrantAuthenticator: {
    offset: 12 #in seconds?
  }
};
```
Also should the config be represented in seconds or milliseconds?

**Comment by bakerac4** [comment]
Well we could probably do both. If its specified in the oAuth2PasswordGrantAuthenticator, then it uses that otherwise it falls back to the root level config. Also I would think milliseconds because that is what the offset is currently and it would provide more granular control. Thoughts?

**Comment by marcoow** [comment]
This should be a property that can be set on the authenticator itself, e.g.

```js
// app/authenticators/oauth2.js
import OAuth2PasswordGrant from 'ember-simple-auth/authenticators/oauth2-password-grant';

export default OAuth2PasswordGrant.extend({
  tokenRefreshOffset: 12000
});
```

Since 1.0, all configuration that relates to specific classes that applications need to define anyway is done in these classes itself, similar to how you'd configure e.g. an Ember Data adapter.

**Comment by Charizard** [comment]
Cool. Makes sense :+1: Will come with a PR soon.

**Comment by marcoow** [comment]
There's one issue with this which I didn't really recognize until just now - the current solution which uses a random offset was implemented in order to try to avoid multiple token refresh requests from multiple tabs or windows where actually one would be sufficient. When configuring a static offset as suggested with the PR one would always get one refresh request per tab/window as they all fire at exactly the same time. An alternative solution would be to allow to configure min and max offsets or to add a property that returns the offset and that could be e.g. defined like this then:

```js
tokenRefreshOffset() {
  const min = 5;
  const max = 10;
  return (Math.floor(Math.random() * min) + (max - min)) * 1000
}.volatile()
```

**Comment by Charizard** [comment]
Isn't the solution for multiple tab refreshes actually to have a `isRefreshing` property and tracking when the token is being refreshed?

Having a random offset is a bad solution, Right? Correct me if I am wrong.

**Comment by marcoow** [comment]
The problem is that when syncing via a flag in localStorage you might run into a situation where token refreshing is disabled forever:

* authenticator in tab a starts refreshing and sets `isRefreshing` to true
* authenticator in tab b sees that `isRefreshing` is true and doesn't refresh itself
* tab a is closed before the authenticator finished refreshing and `isRefreshing` is never set to false again
* later when the next refresh is due: authenticator in tab b sees that `isRefreshing` is true and doesn't refresh itself

Also even when using an `isRefreshing` flag all tabs would trigger refreshing at the same time so all authenticators would access the `isRefreshing` flag at the same time which would potentially lead to race conditions.

**Comment by Charizard** [comment]
We had a similar situation in our old application. But, we solved it using a expiry for the `isRefreshing` boolean. Which would be like 10 - 20 seconds.

**Comment by marcoow** [comment]
But then you still have the race conditions where multiple authenticators in multiple tabs/windows read the `isRefreshing` flag at the same time and all read a value of `false` in which case all of them would trigger a refresh request. In order to prevent that you'd need sth. that randomizes the time just a bit which in turn would be similar to the current solution then.

**Comment by bakerac4** [comment]
A minimum refresh amount would solve my use case just fine. And that would still keep the random number so the refreshing in multiple tabs would not all happen at the same time.

**Comment by marcoow** [comment]
What do you mean by _"minimum refresh amount"_?

**Comment by bakerac4** [comment]
Something like this
`const offset = (Math.floor(Math.random() * this.get('minimumRefreshTime')) + (this.get('maximumRefreshTime') - this.get('minimumRefreshTime'))) * 1000;`

I don't need to set the offset exactly to achieve what I wanted from this issue

**Comment by Charizard** [comment]
@marcoow But even now, when multiple authenticators in two different tabs tries to refresh the token at the same time (the scheduled `offset` for both tabs is the same), then one would succeed and the other would fail (since the refresh token is already expired as it is used by the previous tab) leaving the session invalidated in all tabs.

Another case for this would be two tabs opening at the same time after the `access_token` has expired.

**Comment by Charizard** [comment]
Also @marcoow, I have updated #840 with `minRefreshOffset` and `maxRefreshOffset` configs.
