### ISSUE TITLE
Local storage with multiple tabs

### ISSUE THREAD

**Issue by bakura10** [simplabs/ember-simple-auth#91]
Hi,

I have a strange behaviour, I'm not sure it comes from Ember-Simple-Auth though. If I open my website in one tab, and then open the same in another tab, most of the values from the local storage are gone excepting "access_token" and "authenticator", which in turn throws an exception.

Can you try if you can reproduce the error?

**Comment by erichonkanen** [comment]
@marcoow hello, I am having similar issue in a fork of ember-cli-simple-auth-token... I was just about to submit my PR when I discovered that opening a 2nd tab instantly boots me out of both tabs...

where should I even start to look for what causes that? any suggestions on what it could be? https://github.com/erichonkanen/ember-cli-simple-auth-token

thanks!

**Comment by marcoow** [comment]
@erichonkanen ember-cli-simple-auth-token isn't actually part of Ember Simple Auth but an extension library that's [maintained separately here](https://github.com/jpadilla/ember-cli-simple-auth-token).

The kind of problem you describe is usually caused by custom authenticators with a missing or wrong implementation of the `restore` method.
